/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['.clear-both[_ngcontent-%COMP%] {\n  clear: both;\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FkaWN0aXovRG9jdW1lbnRzL1Byb2plY3RzL2FuZ3VsYXIvc3JjL2FwcC9hcHAuY29tcG9uZW50Lmxlc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvYWRpY3Rpei9Eb2N1bWVudHMvUHJvamVjdHMvYW5ndWxhci9zcmMvYXBwL2FwcC5jb21wb25lbnQubGVzcyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7In0=
