/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './app.component.less.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './app.component';
import * as i3 from './button/button.component.ngfactory';
import * as i4 from './button/button.component';
const styles_AppComponent:any[] = [i0.styles];
export const RenderType_AppComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,styles:styles_AppComponent,
    data:{}});
export function View_AppComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵeld(0,(null as any),
      (null as any),5,'div',([] as any[]),(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i1.ɵted((null as any),['\n  '])),(_l()(),
      i1.ɵeld(0,(null as any),(null as any),2,'app-button',([] as any[]),(null as any),
          [[(null as any),'onChangeBtnValue'],[(null as any),'onSaveBtnValue']],(_v,
              en,$event) => {
            var ad:boolean = true;
            var _co:i2.AppComponent = _v.component;
            if (('onChangeBtnValue' === en)) {
              const pd_0:any = ((<any>_co.changeValue($event)) !== false);
              ad = (pd_0 && ad);
            }
            if (('onSaveBtnValue' === en)) {
              const pd_1:any = ((<any>_co.saveValue($event)) !== false);
              ad = (pd_1 && ad);
            }
            return ad;
          },i3.View_ButtonComponent_0,i3.RenderType_ButtonComponent)),i1.ɵdid(114688,
      (null as any),0,i4.ButtonComponent,([] as any[]),(null as any),{onChangeBtnValue:'onChangeBtnValue',
          onSaveBtnValue:'onSaveBtnValue'}),(_l()(),i1.ɵted((null as any),['\n  '])),
      (_l()(),i1.ɵted((null as any),['\n'])),(_l()(),i1.ɵted((null as any),['\n\n']))],
      (_ck,_v) => {
        _ck(_v,4,0);
      },(null as any));
}
export function View_AppComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'app-root',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i1.ɵdid(49152,(null as any),0,i2.AppComponent,([] as any[]),(null as any),(null as any))],
      (null as any),(null as any));
}
export const AppComponentNgFactory:i1.ComponentFactory<i2.AppComponent> = i1.ɵccf('app-root',
    i2.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FkaWN0aXovRG9jdW1lbnRzL1Byb2plY3RzL2FuZ3VsYXIvc3JjL2FwcC9hcHAuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2FkaWN0aXovRG9jdW1lbnRzL1Byb2plY3RzL2FuZ3VsYXIvc3JjL2FwcC9hcHAuY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvYWRpY3Rpei9Eb2N1bWVudHMvUHJvamVjdHMvYW5ndWxhci9zcmMvYXBwL2FwcC5jb21wb25lbnQuaHRtbCIsIm5nOi8vL1VzZXJzL2FkaWN0aXovRG9jdW1lbnRzL1Byb2plY3RzL2FuZ3VsYXIvc3JjL2FwcC9hcHAuY29tcG9uZW50LnRzLkFwcENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjwhLS1UaGUgY29udGVudCBiZWxvdyBpcyBvbmx5IGEgcGxhY2Vob2xkZXIgYW5kIGNhbiBiZSByZXBsYWNlZC4tLT5cbjxkaXY+XG4gIDxhcHAtYnV0dG9uXG4gICAgICAgICAgKG9uQ2hhbmdlQnRuVmFsdWUpID0gXCJjaGFuZ2VWYWx1ZSgkZXZlbnQpXCJcbiAgICAgICAgICAob25TYXZlQnRuVmFsdWUpICAgPSBcInNhdmVWYWx1ZSgkZXZlbnQpXCI+XG4gIDwvYXBwLWJ1dHRvbj5cbjwvZGl2PlxuXG4iLCI8YXBwLXJvb3Q+PC9hcHAtcm9vdD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7OztvQkNBbUUsdUNBQ25FO01BQUE7TUFBQSw4QkFBSyx5Q0FDSDthQUFBO1VBQUE7dUJBQUE7WUFBQTtZQUFBO1lBQ1E7Y0FBQTtjQUFBO1lBQUE7WUFDQTtjQUFBO2NBQUE7WUFBQTtZQUZSO1VBQUEsbUVBQUE7TUFBQTtVQUFBLGtDQUVpRDtNQUNwQyx1Q0FDVDs7UUFKSjs7OztvQkNGRjtNQUFBO2FBQUE7Ozs7In0=
