/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = ['@color : black;\n.div-element[_ngcontent-%COMP%] {\n    width: 140px;\n    border : 1px double @color;\n    padding: 10px;\n    .input-element {\n        margin-left: 4px;\n    }\n    .button-element {\n        margin-left: 4px;\n        .button {\n            width: 41px;\n        }\n    }\n}'];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL2FkaWN0aXovRG9jdW1lbnRzL1Byb2plY3RzL2FuZ3VsYXIvc3JjL2FwcC9idXR0b24vYnV0dG9uLmNvbXBvbmVudC5sZXNzLnNoaW0ubmdzdHlsZS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL2FkaWN0aXovRG9jdW1lbnRzL1Byb2plY3RzL2FuZ3VsYXIvc3JjL2FwcC9idXR0b24vYnV0dG9uLmNvbXBvbmVudC5sZXNzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
